### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 121.04 GiB (GPU 0; 47.54 GiB total capacity; 2.57 GiB already allocated; 13.33 GiB free; 32.50 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by WesLee88524** [dvl-tum/SUSHI#11]
Hello,when I training use config like this 
![image](https://github.com/dvl-tum/SUSHI/assets/25226447/bdbdd33f-353b-43a6-bdc7-906cfbe26bb0)

I use RTX 6000 GPU and torch=1.8.1+cu111

The error "CUDA out of memory" always occurs! It didn't work even if I set PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32

Do you know if it related to code contents or not? Or how can I fix it?
========================================================
...
Tracking MOT17-02-SDP
Tracking MOT17-02-FRCNN
Tracking MOT17-02-DPM
Tracking MOT17-04-SDP
Tracking MOT17-04-FRCNN
Tracking MOT17-04-DPM
Traceback (most recent call last):
  File "/home/hisham/anaconda3/envs/SUSHI/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hisham/anaconda3/envs/SUSHI/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/hisham/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "scripts/main.py", line 42, in <module>
    hicl_tracker.train()
  File "/home/hisham/yuhaoli/code/SUSHI/./src/tracker/hicl_tracker.py", line 456, in train
    _, _ = self.track(self.val_dataset, output_path=osp.join(self.config.experiment_path, 'oracle'), mode='val', oracle=True)
  File "/home/hisham/yuhaoli/code/SUSHI/./src/tracker/hicl_tracker.py", line 548, in track
    hicl_graphs, _, logs_all = self.hicl_forward(hicl_graphs = hicl_graphs, 
  File "/home/hisham/yuhaoli/code/SUSHI/./src/tracker/hicl_tracker.py", line 333, in hicl_forward
    curr_batch, _ = self._hicl_to_curr(hicl_graphs=hicl_graphs)  # Create curr_graphs from hierarachical graphs            
  File "/home/hisham/yuhaoli/code/SUSHI/./src/tracker/hicl_tracker.py", line 185, in _hicl_to_curr
    batch.pruning_score = compute_giou_fwrd_bwrd_motion_sim(batch, motion_pred)
  File "/home/hisham/yuhaoli/code/SUSHI/./src/utils/motion_utils.py", line 90, in compute_giou_fwrd_bwrd_motion_sim
    fwrd_start_box = fwrd_pred[row].gather(1, t_diff_fwrd[:,None, None].expand(-1, -1, 4))[:, 0]
RuntimeError: CUDA out of memory. Tried to allocate 121.04 GiB (GPU 0; 47.54 GiB total capacity; 2.57 GiB already allocated; 13.33 GiB free; 32.50 GiB reserved in total by PyTorch)

**Comment by ocetintas** [comment]
Hi, you are simply running out of memory in your GPU. Maybe try to reduce the batch size with --num_batch, or run SUSHI with a fewer number of frames e.g. 128. This should drop the performance slightly but you should still easily reach state of the art results.

**Comment by WesLee88524** [comment]
> 

I change the number of frames to 128,it worked!

But I am still wondering why I have 40GB of memory but it appears the error of out of memory.

**Comment by WesLee88524** [comment]
Hi, what kind of GPU you used to train? How long will it trains last? I have trained it on a RTX A6000 GPU more than 2days ,is it right?

**Comment by ocetintas** [comment]
We used an RTX8000. Depending on the parameters, training lasts between 12 hours to 2 days.

**Comment by tobymuller233** [comment]
> We used an RTX8000. Depending on the parameters, training lasts between 12 hours to 2 days.

Hi, I ran into the GPU memory issue, too. I use RTX A6000 with 49GB capacity. But I failed to train the model from scratch under the config below:

- number of levels: 7
- number of frames: 128
- BATCH_SIZE: 1 # one batch per GPU
The training fails when unfreezing the fifth level, where approximately 51GB were required.
Is there any optimization methods to overcome this issue?

**Comment by ocetintas** [comment]
Which dataset are you using this on? Because for the datasets that we experiment on, this shouldn't cause a problem. If the scene is very crowded in your data, I can see this being a problem though. In that case, I'd recommend, reducing the number of hierarchy levels and frames. 

One last thing, note that batch size 1 is not too bad for graph models. Because a single data sample already contains thousands of nodes and edges; hence the training will be stable. Best of luck!

**Comment by tobymuller233** [comment]
> Which dataset are you using this on? Because for the datasets that we experiment on, this shouldn't cause a problem. If the scene is very crowded in your data, I can see this being a problem though. In that case, I'd recommend, reducing the number of hierarchy levels and frames.
> 
> One last thing, note that batch size 1 is not too bad for graph models. Because a single data sample already contains thousands of nodes and edges; hence the training will be stable. Best of luck!

I'm using MOT20 with byte065 detections. I modified the number of levels to 7 and frames to 128, even if i tried 64 (number of frames per level as 2, 4, 8, 16, 32, 32, 64) the GPU memory is also insufficient. During all these tries, I kept the batch size to be 1. I saw in the paper you do experiments on MOT20 too, so I thought there won't be trouble training on it.
